envVarGroups:
  - name: blog-backend-secrets
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: MONGO_DB_URL
        sync: false # Paste your raw mongodb+srv:// string securely in Render's dashboard
      - key: JWT_SECRET
        sync: false # Paste your secret string securely in Render's dashboard
      - key: RABBIT_MQ
        sync: false # Paste your cloud AMQP string securely in Render's dashboard

services:
  # 1. Public API Gateway
  - type: web
    name: api-gateway
    runtime: docker
    plan: free
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    envVars:
      - key: PORT
        value: "3000"
      - fromGroup: blog-backend-secrets
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: blog-redis
          property: connectionString
      - key: AUTH_SERVICE_URL
        value: http://auth-service:4000
      - key: MEDIA_SERVICE_URL
        value: http://media-service:5000
      - key: POST_SERVICE_URL
        value: http://post-service:6000
      - key: COMMENT_SERVICE_URL
        value: http://comment-service:7000

  # 2. Private Auth Service
  - type: private
    name: auth-service
    runtime: docker
    plan: free
    dockerfilePath: ./auth-service/Dockerfile
    dockerContext: ./auth-service
    envVars:
      - key: PORT
        value: "4000"
      - fromGroup: blog-backend-secrets
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: blog-redis
          property: connectionString

  # 3. Private Media Service
  - type: private
    name: media-service
    runtime: docker
    plan: free
    dockerfilePath: ./media-service/Dockerfile
    dockerContext: ./media-service
    envVars:
      - key: PORT
        value: "5000"
      - fromGroup: blog-backend-secrets
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: blog-redis
          property: connectionString

  # 4. Private Post Service
  - type: private
    name: post-service
    runtime: docker
    plan: free
    dockerfilePath: ./post-service/Dockerfile
    dockerContext: ./post-service
    envVars:
      - key: PORT
        value: "6000"
      - fromGroup: blog-backend-secrets
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: blog-redis
          property: connectionString

  # 5. Private Comment Service
  - type: private
    name: comment-service
    runtime: docker
    plan: free
    dockerfilePath: ./comment-service/Dockerfile
    dockerContext: ./comment-service
    envVars:
      - key: PORT
        value: "7000"
      - fromGroup: blog-backend-secrets
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: blog-redis
          property: connectionString

  # 6. Internal Redis Instance
  - type: keyvalue
    name: blog-redis
    plan: free
    ipAllowList: []